/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author RenatoPC
 */
public class vistaAfiliados extends javax.swing.JFrame {

    /**
     * Creates new form vistaAfiliados
     */
    public vistaAfiliados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanelAfiliados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaAfiliados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnCancelarAfiliacion = new javax.swing.JButton();
        btnPromociones = new javax.swing.JButton();
        jPanelPromociones = new javax.swing.JPanel();
        txtNombreAfiliado = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePromociones = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnRetroceder = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCargar = new javax.swing.JMenuItem();
        jMenuItemGuardar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablaAfiliados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablaAfiliados.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTablaAfiliados);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Afiliados");

        btnCancelarAfiliacion.setText("Cancelar Afiliación");

        btnPromociones.setText("Desglose de Promociones");

        javax.swing.GroupLayout jPanelAfiliadosLayout = new javax.swing.GroupLayout(jPanelAfiliados);
        jPanelAfiliados.setLayout(jPanelAfiliadosLayout);
        jPanelAfiliadosLayout.setHorizontalGroup(
            jPanelAfiliadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(jPanelAfiliadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAfiliadosLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanelAfiliadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelAfiliadosLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelAfiliadosLayout.createSequentialGroup()
                            .addGap(140, 140, 140)
                            .addComponent(btnCancelarAfiliacion)
                            .addGap(81, 81, 81)
                            .addComponent(btnPromociones)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelAfiliadosLayout.setVerticalGroup(
            jPanelAfiliadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(jPanelAfiliadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAfiliadosLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(8, 8, 8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addGroup(jPanelAfiliadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCancelarAfiliacion)
                        .addComponent(btnPromociones))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jLayeredPane1.add(jPanelAfiliados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 480));

        jPanelPromociones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombreAfiliado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNombreAfiliado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelPromociones.add(txtNombreAfiliado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 630, 30));

        jTablePromociones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePromociones.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTablePromociones);

        jPanelPromociones.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 60, 610, 410));

        jLayeredPane1.add(jPanelPromociones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 480));

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 480));

        btnRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icos/flechaAtras.png"))); // NOI18N
        jMenuBar1.add(btnRetroceder);

        jMenu1.setText("Cargar/Guardar");

        jMenuItemCargar.setText("Cargar Datos");
        jMenu1.add(jMenuItemCargar);

        jMenuItemGuardar.setText("Guardar Datos");
        jMenu1.add(jMenuItemGuardar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarAfiliacion;
    public javax.swing.JButton btnPromociones;
    public javax.swing.JMenu btnRetroceder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItemCargar;
    public javax.swing.JMenuItem jMenuItemGuardar;
    public javax.swing.JPanel jPanelAfiliados;
    public javax.swing.JPanel jPanelPromociones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTablaAfiliados;
    public javax.swing.JTable jTablePromociones;
    public javax.swing.JLabel txtNombreAfiliado;
    // End of variables declaration//GEN-END:variables
}
